//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend_12102025.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookEdition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookEdition()
        {
            this.BookImages = new HashSet<BookImage>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int BookEditionId { get; set; }
        public int BookTitleId { get; set; }
        public string ISBN { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string CoverImage { get; set; }
        public string ExtraDescription { get; set; }
    
        public virtual BookTitle BookTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookImage> BookImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
