//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend_12102025.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookImage
    {
        public int ImageId { get; set; }
        public int BookEditionId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual BookEdition BookEdition { get; set; }
    }
}
